### ISSUE TITLE
Weird behavior of the search

### ISSUE THREAD

**Issue by guidogast** [harshzalavadiya/react-multi-select-component#10]
During testing the component, I've found a weird issue when searching. This is reproducible on your own CodeSanbox example.

When I type, the order of the items change and the search string doesn't represent the expected result(s). Could you take a look at this?

GIF for clarity: https://i.imgur.com/hZStnR7.gifv

**Comment by harshzalavadiya** [comment]
@guidogast,

as of now it uses [fuzzy search/](https://github.com/harshzalavadiya/react-multi-select-component/blob/master/src/lib/fuzzy-match-utils.tsx) instead of simple string match for better UX although you can customize this behaviour by overriding `filterOptions` prop

I was planning to make fuzzy search secondary to reduce bundle size even more and replace it with normal search as many users don't need this or know about this feature at all

**Comment by guidogast** [comment]
@harshzalavadiya In that case, could you update the documentation with an example of an alternative filter using the `filterOptions` prop? Since it's quite unclear on how it should work.

**Comment by harshzalavadiya** [comment]
@guidogast Sure, I'll try to do that today once I get some free time

**Comment by harshzalavadiya** [comment]
Update: Sorry, I still am occupied with work right now, I'll try to do it as soon as I'll get some time

**Comment by harshzalavadiya** [comment]
Hi @guidogast,

#### Why this logic
General search will throw error when there's even one word not matching, that can be frustrating when users try to find something on dropdown, for example “Julien” and the common spelling “Julian”, only one operation is needed, a substitution of “a” for “e.”

### How this works
1. Convert search query and list options both into alphanumeric + uppercase for example `The_Quick Brown Fox` will be converted to `THEQUICKBROWNFOX`
2. Second task is to calculate similarity score between two strings using dynamic programming algorithm
3. Once you are done finding similarity scores for complete list filter it if score matches entire string with with a slight affordance for transposition or extra characters.
4. Sort filtered list by scores high to low
5. return qualified options

#### References
- https://medium.com/@julientregoat/an-introduction-to-fuzzy-string-matching-178805cca2ab

> 📋 This algorithm is not written or implemented by me and full credit goes to https://github.com/Khan/react-multi-select as mentioned in this project's README.md and seems they got inspiration from https://react-select.com/

I have added custom filter logic example on [docs](https://github.com/harshzalavadiya/react-multi-select-component#-custom-filter-logic)
