### ISSUE TITLE
automatic close

### ISSUE THREAD

**Issue by leosv123** [harshzalavadiya/react-multi-select-component#103]
The select options doesnt close automatically when a option is selected it needs to closed manually by clicking on other side of screen to close the options bar, how can we make it to close automaticallly

**Comment by leosv123** [comment]
automatic close on selecting an multi option

**Comment by harshzalavadiya** [comment]
@leosv123 by default component's behaviour is to allow users to select multiple options at a time so it would not close automatically but *I think the options you might be looking for is `shouldToggleOnHover` prop*
