### ISSUE TITLE
Search Clear Icon not showing

### ISSUE THREAD

**Issue by Kannndev** [harshzalavadiya/react-multi-select-component#104]
In Example gif there is a clear button on search input but that is not showing up

**Comment by harshzalavadiya** [comment]
@Kannndev,

if you mean by below highlighted cross button
![image](https://user-images.githubusercontent.com/5774849/90774313-e8a1f280-e314-11ea-8985-cc7710eb97ae.png)
behind the scenes it's just `<input type="search" />` that chromium based browser shows clear button by default but other browsers might behave differently

**Comment by Kannndev** [comment]
Can we add that as a feature please so that it could be a cross browser supported one. If needed I can do and raise Pr for that?

**Comment by harshzalavadiya** [comment]
@Kannndev sure I'll be happy to have a PR

the only thing is it should be very minimal since, the first priority for this component is to be very lean and simple

**Comment by Kannndev** [comment]
Sure will keep it minimal. Thanks :)

**Comment by Kannndev** [comment]
@harshzalavadiya I have raised a Pr for the same. Please review. 

  Filesizes after the changes.
  brotli      gzip        none     
  3.25 kb  3.64 kb  9.48 kb

**Comment by harshzalavadiya** [comment]
@Kannndev 

Thanks for the PR,
I'll am bit packed this week so I'll try to Review and Merge it this weekend

**Comment by harshzalavadiya** [comment]
🎉 Released in `v3.0.2` 

Thank you @Kannndev for the PR
