### ISSUE TITLE
Click outside to close not working with itemRenderer

### ISSUE THREAD

**Issue by mkhbragg** [harshzalavadiya/react-multi-select-component#118]
If 'Select All' was the most recent option selected, then the dropdown does not close when you click outside. Please see the gif below and relevant code [sandbox](https://codesandbox.io/s/festive-mclean-0k7yx?file=/src/App.js). Notice that click-outside-to-close works well when the most recently clicked option is not the 'select all' item 🧐 

![bug react-multi-select-component](https://user-images.githubusercontent.com/5139784/91209232-6b41fd80-e6d9-11ea-91b4-13ce9ac38f57.gif)

**Comment by mkhbragg** [comment]
Oh and the `ItemRenderer` should probably be `itemRenderer`, no?

**Comment by harshzalavadiya** [comment]
@mkhbragg
thanks for reporting this,
I'll look into this over weekends

> Oh and the `ItemRenderer` should probably be `itemRenderer`, no?
Yes, I also wanted to rename props that are not in camelCase but as of now I can't do that without breaking it for existing users so might be in next major release :smile:

**Comment by mkhbragg** [comment]
> @mkhbragg
> thanks for reporting this,
> I'll look into this over weekends

Sounds good! 🙏 

> > Oh and the `ItemRenderer` should probably be `itemRenderer`, no?
> 
> Yes, I also wanted to rename props that are not in camelCase but as of now I can't do that without breaking it for existing users so might be in next major release 😄

Makes sense!

**Comment by ahmedsamirbek** [comment]
I have a problem when i started with init values it can't be editied ... how can i make this 
for example( when i open multi select box  i wil find 3 items checked  i need to edit them how ?! )

**Comment by harshzalavadiya** [comment]
Fixed in `v3.0.8`
