### ISSUE TITLE
starting with some checked items cannot edit them

### ISSUE THREAD

**Issue by ahmedsamirbek** [harshzalavadiya/react-multi-select-component#120]
I have a problem when i started with init values it can't be editied ... how can i make this
for example( when i open multi select box i wil find 3 items checked i need to edit them how ?! )

**Comment by ahmedsamirbek** [comment]
I mean pre selected items

**Comment by ahmedsamirbek** [comment]
try to put it on example to understand what i mean 
selected.push({ label: "Grapes 🍇", value: "grapes" })

**Comment by harshzalavadiya** [comment]
@ahmedsamirbek 

options and selected both should be handled seprately, if you want pre-selected values you have to use it like below

example: https://codesandbox.io/s/eloquent-field-ecsqo?file=/src/App.js
