### ISSUE TITLE
No Clear icon for clearing all selected items

### ISSUE THREAD

**Issue by Sowjanya-msft** [harshzalavadiya/react-multi-select-component#130]

**Comment by harshzalavadiya** [comment]
Hi @Sowjanya-msft,

You can unselect all items by double checking and unchecking on select all although clear all button might also be a good idea, i'll work on this when I'll get some time, also PR's are welcome if you are intrested

**Comment by ankursnh023** [comment]
Hi @harshzalavadiya 

Any update on this? Need this feature urgently.

**Comment by harshzalavadiya** [comment]
@ankursnh023 

TBH, this might take a while since I'm very occupied nowadays with office work and I get a very little time to work on new features

**Comment by Kannndev** [comment]
@harshzalavadiya I can pick this up if you have an idea of where the button needs to be placed.

**Comment by harshzalavadiya** [comment]
@Kannndev icon can be before down arrow

**Comment by Kannndev** [comment]
Raised PR #153 . Please review

**Comment by harshzalavadiya** [comment]
Released v3.0.4
