### ISSUE TITLE
Dropdown content position

### ISSUE THREAD

**Issue by arpinegaranyan** [harshzalavadiya/react-multi-select-component#132]
I change the position of the dropdown content using css styles but cannot change the direction of the icon.

**Comment by harshzalavadiya** [comment]
@arpinegaranyan 

I am not able to get this can you provide highlighted screenshot of what icon?

---

![image](https://user-images.githubusercontent.com/5774849/92458566-322e8080-f1e3-11ea-96d9-a9dbd109cf0d.png)
if it's dropdown arrow icon then you can use css transform to rotate it by targeting `dropdown-heading-dropdown-arrow` class like below
```css
.dropdown-heading-dropdown-arrow {
  transform: rotate(180deg);
}
```

or if you are trying it with RTL this component wasn;t designed for that but should work with css `direction:rtl` you might have to fix it a bit but should work

**Comment by arpinegaranyan** [comment]
Thanks a lot
