### ISSUE TITLE
Feature request: Managed open/close by external state and defaultOpen prop

### ISSUE THREAD

**Issue by guido-visser** [harshzalavadiya/react-multi-select-component#137]
Awesome work! Might I request a feature for 4.0? 

I'd like to see a managed open/closed prop.

It could look like: `<MultiSelect {...props} open={true} />`. This could then be managed by external state. What would be a perfect addon to this is another prop called: `defaultOpen`, that when true, if the component is mounted, it opens the dropdown automatically. The `defaultOpen` would only work when the `open` prop is not passed.

**Comment by harshzalavadiya** [comment]
Good Idea, This might be useful

**Comment by milojevic1991** [comment]
Hi harshzalavadiya, I agree with @guido-visser ,  open/close prop would be a really important feature. I'm using your library, and I think it's great, only this feature missing to complete an overall great package!

**Comment by harshzalavadiya** [comment]
@guido-visser, @milojevic1991 
I have added `isOpen` and `defaultIsOpen` prop do try it out and let me know if there's any feedback
