### ISSUE TITLE
Feature request: Select all even when filter is active

### ISSUE THREAD

**Issue by JiriSko** [harshzalavadiya/react-multi-select-component#143]
Hi,

thanks for your great component. Could be possible to show _Select all_ checkbox even when search string is entered? It's useful when you want to quickly select for example items with some pre/postfix.

**Comment by Kannndev** [comment]
@harshzalavadiya I can pick this up.

**Comment by Kannndev** [comment]
Can you please assign it to me

**Comment by harshzalavadiya** [comment]
@Kannndev sure

**Comment by Kannndev** [comment]
@harshzalavadiya have raised PR #151 . Can you please review and let me know if any change is needed

**Comment by harshzalavadiya** [comment]
@Kannndev

Overall LGTM Thank you,

I'll merge and release this next week since, I'm bit of occupied

**Comment by Kannndev** [comment]
Thanks

**Comment by Kannndev** [comment]
Updated PR #152

**Comment by harshzalavadiya** [comment]
Released v3.0.4
