### ISSUE TITLE
Call function & setSelected in onchange ? 

### ISSUE THREAD

**Issue by iMinosGFX** [harshzalavadiya/react-multi-select-component#15]
Hello, 
I would need to call another function (like handleSelectedChange) to update another state related to the setSelected.I was thinking of doing this in a function and calling it in the onChange, but unfortunately I can't figure out how to do it... Is this possible? 
like : 
onChange={{() => setSelected, handleSelectedChange}} ?

**Comment by harshzalavadiya** [comment]
Hi @iMinosGFX 

You can do it something like this

```jsx
onChange={d => {
  setSelected(d);
  console.log("do something else with", d);
}}
```
