### ISSUE TITLE
Search input text does not allow keyboard tab spaces

### ISSUE THREAD

**Issue by adomrockie** [harshzalavadiya/react-multi-select-component#155]
Thanks for this , but I think there is an issue with entering spaces in your search text.

If this is by design, then can you let me know how i can override this function. I have a drop down with a long text that require filtering using more than one text value.

Thanks

**Comment by harshzalavadiya** [comment]
@adomrockie by default it uses fuzzy search, so whitespaces will be discarded, but you are free to implement your own custom logic

Here's how to do it
https://github.com/harshzalavadiya/react-multi-select-component#-custom-filter-logic

**Comment by adomrockie** [comment]
What I meant is that, in your component typing in the search box does not allow spaces...eg. typing "Orange is sweet" is not supported. I have already implemented the customFilterLogic method and the filter value is already set without white space.

**Comment by harshzalavadiya** [comment]
@adomrockie 

I got it not certainly it's a bug happening due to event bubbled to parent

**Comment by harshzalavadiya** [comment]
Thanks for reporting v3.0.3 should fix this issue

**Comment by harshzalavadiya** [comment]
Reopening due to issue is back in v4
