### ISSUE TITLE
Bug: Since 3.0.4 expanding the drop down clears the contents.

### ISSUE THREAD

**Issue by Adam-STaC-Solutions** [harshzalavadiya/react-multi-select-component#165]
I believe this may be linked to the addition of a clear button. 

In Chrome this now wipes the selection just by clicking anywhere to expand the drop down.

**Comment by harshzalavadiya** [comment]
@Adam-STaC-Solutions 

I'm not able to understand this completely will it be possible for you to send a gif/video on how to reproduce this also what is your chrome version?

**Comment by Adam-STaC-Solutions** [comment]
Hi @harshzalavadiya, unfortunately not as the code is confidential. 

Basically, what seems to be happening is when a user:

- selects entries in the dropdown
- closes the drop down
- the clear icon appears
- (this is all ok)
- if the user opens the drop down again
- it wipes all user selections.

Chrome version Version 85.0.4183.121 (Official Build) (64-bit)

**Comment by Adam-STaC-Solutions** [comment]
I may not have time for a couple of days. But I'd be happy to take a look and try tackling this. 

I'm after my Hacktoberfest tshirt 👍

**Comment by harshzalavadiya** [comment]
@Adam-STaC-Solutions,

I didn't mean of your complete application, I mean minimal reproduction of codesandbox
I tried in current CSB with `create-react-app` so wasn't able to reproduce it

I'm marking this with hacktoberfest, so if someone or you submit a valid PR it will be counted towards hacktoberfest

**Comment by vladpre92** [comment]
@harshzalavadiya I think he means that the selected options won't persist for the second interaction with the dropdown, or in some cases when dropdown disappear.
In my case, selected items persist only if I click outside dropdown. If I click the dropdown or anywhere inside, selected items won't persist.
I've attached a GIF with this behaviour.
I tested with Chrome and Safari. Same issue. Maybe we're doing something wrong?

Thanks!

![Screen Recording 2020-10-19 at 13 55 06](https://user-images.githubusercontent.com/3681654/96442344-a82afc00-1213-11eb-86d5-b112eb06fcd7.gif)

**Comment by Adam-STaC-Solutions** [comment]
@vladpre92 Exactly that.

**Comment by harshzalavadiya** [comment]
@vladpre92 @Adam-STaC-Solutions,

I tried reproducing in mac safari and chrome both but wasn;t able to so I have added `e.stopPropagation();` to prevent bubbling can anyone try installing `react-multi-select-component@canary` and see if this fixes the issue?

**Comment by harshzalavadiya** [comment]
Hopefully this might be fixed in new version / might be simple state management issue , feel free to reopen if sandbox is available
Closing for now

**Comment by thetrime** [comment]
This appears to still be a problem in Safari 14.0.3, but I'm not sure whose fault it is. The general problem is that clicking on the div which contains the clear icon triggers an onClick on the button, even if you don't click on the button itself. 

It seems to require more than just this - a very quick test with plain HTML doesn't reproduce it, but I certainly see the same behaviour as @vladpre92 in my app.

On the plus side, you can stop this happening (it seems) by just adding an onClick to the div (that is, the .dropdown-heading) and calling event.prevenDefault().

I'll see if I can come up with a simple sandbox that illustrates the problem

**Comment by thetrime** [comment]
Aha. Specifically, it happens if you have a pattern like this:
```
<label>
   <div>
      <span>This is some text which is not inside the button</span>
   </div>
   <button onClick="alert('clicked')">X</button>
</label>
```

Clicking on the text will trigger the event on the button.

I can't tell if this is what the original author was doing, but it _is_ true that you aren't allowed a div inside a label
