### ISSUE TITLE
unselect pre-selected rows

### ISSUE THREAD

**Issue by Kidist-Abraham** [harshzalavadiya/react-multi-select-component#18]
I want the user to unselect pre-selected options using the UI. 
Given that the `value` prop is set to some options, can the user unselect the value or add additional select? 
Current behavior: 
If the value state is changed programmatically, the select box will be disabled for both adding or removing selected values.

**Comment by Kidist-Abraham** [comment]
Sorry, the form is disabled by a parent component.

**Comment by leosv123** [comment]
But why preselected options can't have ticked in dropdown list?

**Comment by leosv123** [comment]
i mean
const [selected, setSelected] = useState([{value:"mango", label:"mango"]);

Mango is not remained ticked in dropdown menu
