### ISSUE TITLE
Add Button

### ISSUE THREAD

**Issue by VivekRajak2020** [harshzalavadiya/react-multi-select-component#196]
How to add button below select list

**Comment by harshzalavadiya** [comment]
Hi @VivekRajak2020 I didn't got your question properly can you explain it a bit more like with some example?

**Comment by VivekRajak2020** [comment]
How to add button at the bottom of dropdown List
![drop](https://user-images.githubusercontent.com/66259747/97978949-5cbc4480-1df4-11eb-874a-f2a591141c5c.PNG)

**Comment by harshzalavadiya** [comment]
Oh, sorry there's no direct way to do this 😅
As of now there's no plan to add this near future, but you are free to fork the repository and customize it your way,

I think you can look at https://www.npmjs.com/package/@kenshooui/react-multi-select with little bit of customization this might work for you
