### ISSUE TITLE
Enable to fixed the search input when scrolling

### ISSUE THREAD

**Issue by yuvalshim** [harshzalavadiya/react-multi-select-component#197]
@harshzalavadiya Maybe it be better UX to enable to fixed the search input to top of the dropdown.
it feels weird that he disappeared in a scroll.

What do you say?

Maybe add some props: `stickySearchInput: Boolean`

**Comment by harshzalavadiya** [comment]
@yuvalshim
Good suggestion, By default it can be sticky
PR's is welcome

**Comment by harshzalavadiya** [comment]
@yuvalshim `v4.0.0` has introduced permanant sticky searchbar

**Comment by yuvalshim** [comment]
Very nice. Great work
