### ISSUE TITLE
Selected Value is shown in CHIP format

### ISSUE THREAD

**Issue by barakjobs** [harshzalavadiya/react-multi-select-component#198]
Hi,
I am using react-multi-select-component in my project. I want to see the selected values as square shape CHIP on a selection with the delete icon button. If anyone will click on the delete icon that value should remove from the selected value.
if I am using valueRenderer with customValueRender but it is not working as expected.

**Comment by harshzalavadiya** [comment]
Hi @barakjobs 

can you provide not working sandbox.

p.s. Instead of customizing this component for chip, you might be better off with using ready made component like [this one](https://www.npmjs.com/package/react-multiple-select-dropdown-lite) 😄
