### ISSUE TITLE
Keyboard scrolling issue - Can't scroll to the last element

### ISSUE THREAD

**Issue by milojevic1991** [harshzalavadiya/react-multi-select-component#201]
Hi @harshzalavadiya, when you try to scroll(e.g scrolling down) with the keyboard arrow on the opened input element, it only navigating to the second last-child, it will not reach the last dropdown element. The issue is present on the official demo, too.

**Comment by harshzalavadiya** [comment]
@milojevic1991 Thanks for the bug report
Fixed it in `v3.0.6`

**Comment by milojevic1991** [comment]
Hi, @harshzalavadiya Thanks for the fast feedback! One issue though, when the search bar is disabled, or a complete search is disabled too, scroll with the keyboard won't work. 

Keyboard scroll only works when the search is on, and without the focus. It's essential small functionality for all the enterprise apps.

**Comment by harshzalavadiya** [comment]
Okay, I'm reopening this as of now so I can keep track of this

**Comment by harshzalavadiya** [comment]
@milojevic1991 released `v4.0.0`
