### ISSUE TITLE
Dropdown content not closing when clicking outside the component

### ISSUE THREAD

**Issue by Nawazsherif** [harshzalavadiya/react-multi-select-component#206]
**Scenario:**

I selected some of the items in the dropdown and clicked directly on the clear icon, the dropdown content always  stays.

**Expected behaviour**

I want the dropdown content to be closed if I click anywhere on the page.

**Current behaviour**

The dropdown content is getting closed only if I click on the select box.

I see this issue as critical bug. *This makes the user experience so bad.*

**Comment by harshzalavadiya** [comment]
Fixed in `v3.0.7`

**Comment by Nawazsherif** [comment]
Thanks a lot for the quick fix. Works well now.
