### ISSUE TITLE
Alignment issue

### ISSUE THREAD

**Issue by TitusLearn2Code** [harshzalavadiya/react-multi-select-component#23]
![Capture1](https://user-images.githubusercontent.com/21241006/81491856-1ecbe100-92e7-11ea-9c73-984241a04091.PNG)

**Comment by harshzalavadiya** [comment]
@TitusLearn2Code,

This looks like css messup done by css reset or you overriding css in unsafe manner, if you think this is not the case then please provide codesandbox minimal reproduction

**Comment by harshzalavadiya** [comment]
closing due to no response
