### ISSUE TITLE
Dynamic Placeholder Change

### ISSUE THREAD

**Issue by ashraf-commits** [harshzalavadiya/react-multi-select-component#232]
Is there way to change the placeholder with some dynamic names with props, So currently it is there as " select..." 

* Can we make select input box as borderless

**Comment by harshzalavadiya** [comment]
@ashraf-commits sure, If you just want to change select into something elase you can use [internationalization](https://github.com/harshzalavadiya/react-multi-select-component#-internationalization) to customize
