### ISSUE TITLE
defaultIsOpen and isOpen not working

### ISSUE THREAD

**Issue by VivekRajak2020** [harshzalavadiya/react-multi-select-component#242]
I passing props as true but menu is not getting opened by default.

```tsx
                            <MultiSelect
                                options={Area}
                                value={Select}
                                onChange={(options) => SelectHandler(options)}
                                overrideStrings={WorkStrings}
                                filterOptions={filterOptions}
                                disabled={isEmpty(WorkArea) ? true: false }
                                defaultIsOpen={true}
                            />
```

**Comment by harshzalavadiya** [comment]
@VivekRajak2020 I think you might have to use `isOpen` since `defaultIsOpen` might go away when clicked anywhere outside

![Peek 2020-12-10 20-10](https://user-images.githubusercontent.com/5774849/101786424-ecf05680-3b23-11eb-9a3f-04cb1c4c9f96.gif)

**Comment by VivekRajak2020** [comment]
Thanks @harshzalavadiya for the help but passing isOpen as true doesn't open list by default.
I am using following version
"react-multi-select-component": "^3.0.4",

**Comment by harshzalavadiya** [comment]
@VivekRajak2020 please update your dependency to latest (i.e. 3.0.7)

**Comment by harshzalavadiya** [comment]
closing this since issue is already fixed in latest updated package
