### ISSUE TITLE
How to disable Multiselect feature.

### ISSUE THREAD

**Issue by yash-fission** [harshzalavadiya/react-multi-select-component#255]
I am searching for a boolean prop from which I can disable the multi-select feature in the component.

**Comment by harshzalavadiya** [comment]
Hi @yash-fission,

This component is specifically designed for multiple-selection only :wink: , if you want single select best choice will be to use native `<select/>` but if you want it to be searchable then using [react-select](https://react-select.com/) might be a better choice

**Comment by yash-fission** [comment]
Thanks for fast reply, What about a boolean prop from disabling the Search bar?

**Comment by harshzalavadiya** [comment]
it's `disableSearch` you can see all available props [here](https://github.com/harshzalavadiya/react-multi-select-component#-props)
