### ISSUE TITLE
Selected options can be cleared when the component is disabled

### ISSUE THREAD

**Issue by kboni** [harshzalavadiya/react-multi-select-component#289]
Hi @harshzalavadiya.
When I select any number of options and then dynamically set disabled={true} I can still click on the clear-selection "X" button, which clears all selected item, but leaves the component disabled, so the component becomes unusable.
Expected behavior:  No actions (including selection-clearing) should be allowed when the component is disabled.

**Comment by harshzalavadiya** [comment]
@kboni Thanks for reporting I'll check it out

**Comment by harshzalavadiya** [comment]
@kboni latest v3.1.3 should fix this issue

**Comment by kboni** [comment]
Works like a charm. Thanks. Great job. Cheers.
