### ISSUE TITLE
Using object styles instead of tagged templates reduces the output gzipped size with `-200B`

### ISSUE THREAD

**Issue by cristianbote** [harshzalavadiya/react-multi-select-component#3]
Hey @harshzalavadiya,

First of all kudos for this project! Really love the output and the small sizes! 😉 Also love that you chose to use `goober` 😄 thank you for that!

Second, was noticing that you've used _`css`_ function with tagged template and looking at the minified output in here https://unpkg.com/react-multi-select-component@2.0.0/dist/react-multi-select-component.cjs.production.min.js the _space_ occupied by those `\n` and other strings is enormous. 😄 So I've played around a bit with it and if you change the tagged template into object styles, the output is shaved with `-200B`!

The syntax will change as:
```js
css`
  opacity: 1;

  &:hover {
    color: tomato;
  }
`;

// To
css({
  opacity: 1,

  '&:hover': {
    color: 'tomato'
  }
});
```

```sh
Filesizes
                                   brotli   gzip     none     
  ✔ original/react-multi-*.min.js  3.14 kb  3.58 kb  9.93 kb  
  ✔     dist/react-multi-*.min.js  3.00 kb  3.37 kb  8.83 kb
```

Let me know if you're looking to shave that I can open a PR with those changes.

**Comment by harshzalavadiya** [comment]
Hi @cristianbote 
first of all thank you for creating goober it's lighter beyond my imagination 😃
Thanks for pointing out this, It will be really great to make this component lib even lighter, I'll be really happy to have a PR 🎉
