### ISSUE TITLE
Feature Request: custom trigger element

### ISSUE THREAD

**Issue by breynolds-dev** [harshzalavadiya/react-multi-select-component#317]
Just picked up the library and it's been very useful for me, but there was a use case I ran into where I would love to still use all the logic and everything built into using the dropdown, but I want to replace the triggering element with a custom element instead.

Looking over the source and testing it out I was able to replicate sort of what I imagined in a very simplistic solution:
```
      { CustomDropdown?.( { toggleExpanded } ) ?? (
          <div
          className={cn(DropdownHeading, "dropdown-heading")}
          onClick={toggleExpanded}
        >
            <div className="dropdown-heading-value">
            <DropdownHeader />
          </div>
          {isLoading && <Loading />}
          {value.length > 0 && (
            <button
              type="button"
              className={cn(ClearSelectedButton, "clear-selected-button")}
              onClick={handleClearSelected}
              disabled={disabled}
              aria-label={t("clearSelected")}
            >
              {ClearSelectedIcon || <Cross />}
            </button>
          )}
          <FinalArrow expanded={expanded} />
        </div>
      )}
```

just choosing to invoke the `CustomDropdown` method and if it returns something valid it'll use that, otherwise it falls back to the standard.

![2021-03-01 21 56 23](https://user-images.githubusercontent.com/13542564/109595102-7be48d80-7ad9-11eb-9baa-f0d743798167.gif)

The only real issue I ran into was the border surrounding the parent element and I just commented those lines out for the example here, but I just wondered if you've given any thought to something like this?  I'd really love to be able to use it this way

**Comment by harshzalavadiya** [comment]
@breynolds-dev I think you should be able to achieve same result using css overrides + custom renderer, I have unique classnames added to most components just for this reason

https://user-images.githubusercontent.com/5774849/109622172-d4f80400-7b61-11eb-8ba4-61c2af775061.mp4


```css
.dropdown-container {
	border: 0;
	display: inline-block;
}
.dropdown-heading{
	padding: 0;
	height: auto;
}
.dropdown-heading-dropdown-arrow{
	display: none;
}
```

```jsx.diff
<MultiSelect
    options={options}
    value={selected}
+   valueRenderer={() => <button>Dropdown</button>}
    onChange={setSelected}
    labelledBy={"Select"}
  />
```

**Comment by breynolds-dev** [comment]
I will give that a try. The only problem I see is the type is expecting valueRenderer to return a string, could that type be updated to accept a string or JSX.Element?

**Comment by harshzalavadiya** [comment]
`v3.1.4` released
