### ISSUE TITLE
Showing "Select All" even if there are no search results.

### ISSUE THREAD

**Issue by ganesh-sanap** [harshzalavadiya/react-multi-select-component#318]
## Actual Behavior

When user searches & there are no results found for search criteria, dropdown still shows "Select All" option.

On click of "Select All", it does not select anything as there are no results. So, it is confusing to users.

![image](https://user-images.githubusercontent.com/25476310/109599693-a23e1380-7b41-11eb-9f80-52f05eb068bc.png)

## Expected Behavior

When there are no search results found, it should not show "Select All" option.

**Comment by harshzalavadiya** [comment]
@ganesh-sanap yeah, probably add an fallback for `no options` like `react-select`
![no-options](https://user-images.githubusercontent.com/5774849/109625081-e8589e80-7b64-11eb-9ca5-9a13b2168515.png)

**Comment by ganesh-sanap** [comment]
@harshzalavadiya Yes, that will be a great addition!

**Comment by harshzalavadiya** [comment]
@ganesh-sanap released `v3.1.5` should fix this issue
