### ISSUE TITLE
onMenuToggle gets called on first render

### ISSUE THREAD

**Issue by zachtaylor21** [harshzalavadiya/react-multi-select-component#325]
I noticed that the `onMenuToggle` prop gets called on the first render. Is this the intended functionality? To me, it feels like `onMenuToggle` should only be called when the user actually toggles the menu.

**Comment by harshzalavadiya** [comment]
@zachtaylor21 thanks for reporting this, AFAIK must because of useEffect

**Comment by harshzalavadiya** [comment]
@zachtaylor21 released `v3.1.6` should fix this

**Comment by zachtaylor21** [comment]
@harshzalavadiya Awesome, thanks!
