### ISSUE TITLE
overrideStrings syntax

### ISSUE THREAD

**Issue by ltcrawshaw** [harshzalavadiya/react-multi-select-component#336]
I can't seem to get the overRideStrings property to work. It seems to be syntax. Could you share an example of how to override the following key value pair?

 "selectSomeItems": "Select..."

**Comment by harshzalavadiya** [comment]
@ltcrawshaw you can find allowed strings in docs &rarr; https://github.com/harshzalavadiya/react-multi-select-component#-internationalization
