### ISSUE TITLE
Cannot apply custom Icon

### ISSUE THREAD

**Issue by Youn-ha** [harshzalavadiya/react-multi-select-component#343]
<img width="963" alt="스크린샷 2021-03-23 오전 11 27 27" src="https://user-images.githubusercontent.com/49135241/112083674-d352b680-8bca-11eb-959e-2d8cdce73208.png">

**(screen capture above is normal case)**

<img width="968" alt="스크린샷 2021-03-23 오전 11 23 36" src="https://user-images.githubusercontent.com/49135241/112083365-398b0980-8bca-11eb-9ddc-073814bc12dd.png">

**(screen capture above is error case)**

I tried to apply custom Clear icon by using `ClearSelectedIcon`.
But it doesn't work in my environment.
Anytime I use `ClearSelectedIcon`, clear `<button>` gets empty. (like screen capture above)
It would be so thankful if somebody could help me out.
Here's my code below.

``` jsx
  const clearBtnRenderer = () => (
    <>
      // I tried several tags(img tag, text), but nothing worked
      <svg
        width="24"
        height="24"
        fill="none"
        stroke="currentColor"
        strokeWidth="2"
        className="dropdown-search-clear-icon gray"
      >
        <line x1="16" y1="8" x2="8" y2="16"></line>
        <line x1="8" y1="8" x2="16" y2="16"></line>
      </svg>
    <>
  );

  return (
    <div className="a_search_multiselect_box">
      <MultiSelect
        options={optionList}
        value={selected}
        onChange={handleChange}
        ClearSelectedIcon={clearBtnRenderer}
      />
    </div>
  );
};
```

I refered to storybook below.
[react-multi-select Storybook : custom arrow](https://react-multi-select-component.netlify.app/?path=/story/custom-arrow--example-custom-arrow)

**Comment by harshzalavadiya** [comment]
Hi @Youn-ha,

instead of passing as function please pass it as rendered component like below and it should work as expected

```diff
<MultiSelect
  options={options}
  value={selected}
  onChange={setSelected}
  labelledBy={"Select"}
- ClearSelectedIcon={clearBtnRenderer}
+ ClearSelectedIcon={<ClearBtnRenderer/>}
/>
```

**Comment by Youn-ha** [comment]
Hi @harshzalavadiya ,

I tried below -

1.
```jsx
  const clearBtnRenderer = () => (
    <>
      <svg
        width="24"
        height="24"
        fill="none"
        stroke="currentColor"
        strokeWidth="2"
        className="dropdown-search-clear-icon gray"
      >
        <line x1="16" y1="8" x2="8" y2="16"></line>
        <line x1="8" y1="8" x2="16" y2="16"></line>
      </svg>
    <>
  );

  return (
    <div className="a_search_multiselect_box">
      <MultiSelect
        options={optionList}
        value={selected}
        onChange={handleChange}
        ClearSelectedIcon={<clearBtnRenderer />}
      />
    </div>
  );
};
```
**`===> type error : Type 'Element' is not assignable to type 'string | Function'.`**

2.
```jsx
  return (
    <div className="a_search_multiselect_box">
      <MultiSelect
        options={optionList}
        value={selected}
        onChange={handleChange}
        ClearSelectedIcon={() => <clearBtnRenderer />}
      />
    </div>
  );
};
```
**`===> there was no type error, but clear button didn't show up.`**

3.
```jsx
  return (
    <div className="a_search_multiselect_box">
      <MultiSelect
        options={optionList}
        value={selected}
        onChange={handleChange}
        ClearSelectedIcon={() => (
          <svg
            width="24"
            height="24"
            fill="none"
            stroke="currentColor"
            strokeWidth="2"
            className="dropdown-search-clear-icon gray"
          >
            <line x1="16" y1="8" x2="8" y2="16"></line>
            <line x1="8" y1="8" x2="16" y2="16"></line>
          </svg>
        )}
      />
    </div>
  );
```
**`===> this one either.`**

(And sorry btw how can I show subtracted/added code like you in code markdown? I tried to google it but failed to find it)

**Comment by harshzalavadiya** [comment]
@Youn-ha

- First approach is correct *type error* might be due to incorrect TypeScript interface that was defined by me, I have created a PR that should resolve this issue
- you can use backticks with `diff` extension diff files will be automatically highlighted when there's `+` or `-` as first charactor

**Comment by harshzalavadiya** [comment]
released `v3.1.7` should fix this typecheck issue

**Comment by Youn-ha** [comment]
I updated to `v3.1.7` and it works well! Thank you so much

**Comment by prathambhardwaj** [comment]
Hi, I want to create a customized clear icon for selected option, there should be a clear icon for every selected item, is that possible in react-multi-select-component?

**Comment by harshzalavadiya** [comment]
@prathambhardwaj you can do that but I would recommend using [react-select](https://react-select.com)

**Comment by prathambhardwaj** [comment]
Could you please tell me the custom element which can provide the clear icon to every selected item?

**Comment by harshzalavadiya** [comment]
@prathambhardwaj it's `valueRenderer`
