### ISSUE TITLE
Z-Index Issue

### ISSUE THREAD

**Issue by harshamv** [harshzalavadiya/react-multi-select-component#344]
When I focus on the Dropdown It slides below my card component like below

[https://imgur.com/a/QDtqi8o](https://imgur.com/a/QDtqi8o)

I am not able to fix the z-index to overlap on my card component.

**Comment by harshzalavadiya** [comment]
@harshamv this looks like CSS `overflow:hidden` kinda issue on card removing it should resolve issue

![image](https://user-images.githubusercontent.com/5774849/112164207-b393b080-8c13-11eb-8270-c221ea70ca6c.png)
