### ISSUE TITLE
Changing Dropdown Header Title

### ISSUE THREAD

**Issue by emaanhaseem** [harshzalavadiya/react-multi-select-component#358]
Hi I'm a student using this component for a school project, and it has been super helpful so far!
But I'm not sure if `aria-labelledby` and changing the `labelledby` is supposed to change the header title. When inputting `labelledBy="Sort By"` into the MultiSelect component, the dropdown title remains unchanged: "Select...".
Can this be fixed?

**Comment by emaanhaseem** [comment]
Just saw that that's not the function of `aria-labelledby`. However, can this feature still be implemented?

**Comment by harshzalavadiya** [comment]
Hi @emaanhaseem

`aria-labelledby` is an accessablity attribute it is for screen readers, to change text please override `overrideStrings` keys as below https://github.com/harshzalavadiya/react-multi-select-component#-internationalization
