### ISSUE TITLE
Bug: ClearSelectedIcon button not working using keyboard

### ISSUE THREAD

**Issue by tofful** [harshzalavadiya/react-multi-select-component#378]
**Current:**
When user has selected items, 
and user want to delete items by using the keyboard `[Tab]`,
and user focus on `ClearSelectedIcon` button,
and user press `[Enter]` or `[Space]`
then user is not able to remove selected items but it expands the menu instead.

**Desired:**
As a user, I'd like to be able to use the keyboard to delete items when it is focused on `ClearSelectedIcon` and press `[Enter]` or `[Scape]` keys.

![image](https://user-images.githubusercontent.com/1058850/116512069-8ecddf80-a91b-11eb-8be3-2f60be3a0c1c.png)
and
![image](https://user-images.githubusercontent.com/1058850/116512941-f2a4d800-a91c-11eb-90b6-f695b79a945a.png)

**Comment by harshzalavadiya** [comment]
@tofful thanks for reporting this bug, I'll try to fix it in few days

**Comment by harshzalavadiya** [comment]
released `v4.0.2` should fix this issue
