### ISSUE TITLE
Feature request: Options from API when expanding the dropdown

### ISSUE THREAD

**Issue by tofful** [harshzalavadiya/react-multi-select-component#380]
As a developer,
I'd like to call an API to populate the options only if user expands the dropdown menu. (When no options available) if the API already returned the Options then not needed to call it again. 

Use case:
Having 10 multiple Select dropDown in a page where each dropdown fetch its own options from different APIs could be killing if the user didn't even interacted with those Select Dropdown, also it needs another API to fetch the Values, that is why it is more convenient to wait until the user interacted with the Select before populating the Options 

Note:
We have "expanded: true/false) for custom chevrons, maybe the same logic could be applied but exposing an event onExpand() ? 

Let me know if that make sense or if there is already a workaround. 

Thank you very much, I love this multi select library 😍

**Comment by harshzalavadiya** [comment]
@tofful

I'm glad you are enjoying this library, We already have this prop it's `onMenuToggle` which accepts function that will take boolean (state of menu if opened then `true` and `false` on close) that should solve your problem

Storybook Example: https://react-multi-select-component.netlify.app/?path=/docs/basic--example-default

*note to self: add `onMenuToggle` prop in `README.md`*

**Comment by tofful** [comment]
Hi @harshzalavadiya `onMenuToggle` method sounds fantastic! thank you for recommending it and also for adding it to the Readme.md

**Comment by trevor-sutherland** [comment]
> As a developer,
> I'd like to call an API to populate the options only if user expands the dropdown menu. (When no options available) if the API already returned the Options then not needed to call it again.
> 
Hi @tofful, I haven't had luck using an API to populate the options. 

Do you mind sharing how you're doing it? 
when I copy the results of my data transform into an options variable like the example shows it works, but I can't get options={props.options} to work.
