### ISSUE TITLE
Bug: Cannot have duplicate labels

### ISSUE THREAD

**Issue by maejoh** [harshzalavadiya/react-multi-select-component#388]
If you have two options with the same label but different values, selecting one also selects the other. 

I'm using disabled options as headers for different categories, and some categories have options with the same labels but representing different entities. When you toggle one of these labels, both are added/removed from the selection.

**Comment by harshzalavadiya** [comment]
Thanks for the report I'll try to fix in a few days, but PRs are always welcomed 🙂

**Comment by harshzalavadiya** [comment]
@maejoh,

I had time to check looks like it's unlikely if your value if different it should not happen
![Peek 2021-05-19 14-39](https://user-images.githubusercontent.com/5774849/118791284-2f2c7980-b8b4-11eb-9f57-872fdd2942aa.gif)

If you are able to reproduce this then please provide minimal sandbox

**Comment by harshzalavadiya** [comment]
closing this since no response from issue author feel free to comment if issue persists
