### ISSUE TITLE
Required Parameter

### ISSUE THREAD

**Issue by Musadiqkhan-nullbrainer** [harshzalavadiya/react-multi-select-component#393]
I tried adding required parameter but it is not working. Is it possible to have a required parameter just like a basic html select element?

**Comment by harshzalavadiya** [comment]
@Musadiqkhan-nullbrainer 

I'm not sure if HTML5 validation can be directly used with custom components
The hacky way to do this might be like [this](https://codesandbox.io/s/shy-darkness-717bl?file=/src/App.js)

but, your best bet might be to use it with something like [react-hook-form](https://react-hook-form.com/) (Recommended) or [Formik](https://formik.org/)
