### ISSUE TITLE
Search box does not allow "space"

### ISSUE THREAD

**Issue by ganesh-sanap** [harshzalavadiya/react-multi-select-component#400]
## Actual Behavior

When user searches in textbox, it does not allow "space". Maybe `.trim()` is added somewhere in on change handler of search textbox.

![image](https://user-images.githubusercontent.com/25476310/121201687-54e4e700-c892-11eb-81e3-8a3a6613eb20.png)

## Expected Behavior

Search textbox should allow users to enter "space".

**Comment by harshzalavadiya** [comment]
@ganesh-sanap v4.0.1+ has this issue fixed, please update to latest
