### ISSUE TITLE
TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by gagandeep-s** [harshzalavadiya/react-multi-select-component#409]
Getting below error on react v17.0.1

![image](https://user-images.githubusercontent.com/26773871/123126277-e04fa200-d466-11eb-8e3f-4bfe20c719e9.png)

`const [locs, setLocs] = useState([{ label: "Branch 1", value: "1" }, { label: "Branch 2", value: "2" }]);`

`<MultiSelect
                        disableSearch={true}
                        options={locs}
                        value={[locs[0]]}
                        onChange={(e: any) => {}}
                        labelledBy="Select Location"
                      />`

**Comment by gagandeep-s** [comment]
![image](https://user-images.githubusercontent.com/26773871/123127821-412baa00-d468-11eb-90ee-58606b97f299.png)

**Comment by gagandeep-s** [comment]
Another finding:

This component is incompatible with antd Forms

`<Form.Item
                  name="test"
                  label="Test"
                  rules={[
                    {
                      required: true,
                    },
                  ]}
                ><MultipleSelect
                    labelledBy="Select Test"
                    value={[getOptions()[0]]}
                    options={getOptions()}
                    onChange={callback}
                  /></Form.Item>`

**Comment by harshzalavadiya** [comment]
Hi @gagandeep-s,

This doesn't look like react issue at all it's syntax used is the issue you should use options seprately and set value seprately

```jsx.diff
+ const options = [{ label: "Branch 1", value: "1" }, { label: "Branch 2", value: "2" }];
const [locs, setLocs] = useState(options); // This will make all options selected by default
<MultiSelect
  disableSearch={true}
  options={options}
-  value={[locs[0]]}
+ value={locs}
  onChange={setLocs}
  labelledBy="Select Location"
/>
```

**Comment by harshzalavadiya** [comment]
> Another finding:
> 
> This component is incompatible with antd Forms
> 
> `<Form.Item name="test" label="Test" rules={[ { required: true, }, ]} ><MultipleSelect labelledBy="Select Test" value={[getOptions()[0]]} options={getOptions()} onChange={callback} /></Form.Item>`

I'm not sure about antd form but it probably already has multiple select component
This component is genric provides no direct integration with any 3rd party library out of box but you should be able to write custom wrapper around it

**Comment by gagandeep-s** [comment]
Thanks for your input, I've somehow managed it.

**Comment by gagandeep-s** [comment]
> This doesn't look like react issue at all it's syntax used is the issue you should use options seprately and set value seprately

the solution proposed by you is not correct, because the same thing works well without antd form item.

**Comment by harshzalavadiya** [comment]
Not sure, I may have misunderstood it, but whatever works for you
