### ISSUE TITLE
labelledBy prop does not insert customText as placeholder text

### ISSUE THREAD

**Issue by jamesmart77** [harshzalavadiya/react-multi-select-component#429]
Hello,
Super cool component! When adding custom text to `labelledBy`, I would expect the value  I provide to override the default "Select..." value, but that is not happening.

My Implementation
```
<MultiSelect
      className="filter-select"
      options={markets.map(market => ({ label: `${market}`, value: `${market}`}))}
      value={selections.markets}
      onChange={value => handleFilterChange('markets', value)}
      labelledBy="Select Market..."
/>
```

This is what is rendered
![image](https://user-images.githubusercontent.com/29242164/126786106-48b365e7-c451-449b-b9c1-96814ead615f.png)

Let me know if this is something I am doing wrong.

**Comment by harshzalavadiya** [comment]
@jamesmart77 

glad you liked it, `labelledBy` prop is for accessiblity you can use `overrideStrings` to change placeholder

```jsx
<MultiSelect
  options={options}
  value={selected}
  onChange={setSelected}
  labelledBy="Select" // <- for accessiblity
  overrideStrings={{ "selectSomeItems": "Select XYZ..."}} // <- to override strings
/>
```

https://github.com/harshzalavadiya/react-multi-select-component#-internationalization

**Comment by jamesmart77** [comment]
![bitmoji](https://sdk.bitmoji.com/render/panel/21759482-c054-4dc5-aaef-e9ce15cf7e3a-41f39225-5469-45c9-81eb-e9262c9c35ad-v1.png?transparent=1&palette=1&width=246)

Thanks for the quick response!!
