### ISSUE TITLE
Feature Request: select single option

### ISSUE THREAD

**Issue by jeffsmonteiro** [harshzalavadiya/react-multi-select-component#442]
The component is amazing, but when I need to use a simple single select I need to use another component. So, may be a good idea provide the option to this component provide a single option select too.

**Comment by harshzalavadiya** [comment]
Duplicate of #417

@jeffsmonteiro I have been thinking about this for a long time but since this requires some fundamental changes in component, I'll try to add this in near future

PRs are welcome

**Comment by govindsartaj** [comment]
Kind of a hacky way to do it, but you can use `useEffect` to ensure that there is only one option selected. I did it like this:
```javascript

// assuming your selected options are stored in the 'selected' state
const [selected, setSelected] = useState([])

useEffect(() => {
    if (selected.length > 1) {
      setSelected([selected[selected.length - 1]])
    }
}, [selected])
```

**Comment by harshzalavadiya** [comment]
closing this so we can track this on other issue
