### ISSUE TITLE
Disabled styles

### ISSUE THREAD

**Issue by damir-ivanic** [harshzalavadiya/react-multi-select-component#443]
There is no good way to apply styles for the component when it's disabled.
If you click on it while it's disabled it gets a blue outline. That can trick users into thinking it is active but that's something wrong with it. Any thoughts on how to style it?

**Comment by harshzalavadiya** [comment]
issue is fixed currently GitHub is having issues with GitHub Action Builds, I'll create a new release new version as soon as it fixes
