### ISSUE TITLE
Do you have a version of single selection? Since I want to use both multi and single with the same style

### ISSUE THREAD

**Issue by flora8984461** [harshzalavadiya/react-multi-select-component#45]
Thanks for providing this component. It works great.

I am just having a small issue that, since I want to use both multi and single selection in one form with the same style, I wonder if you also have single selection option?

Thank you!

**Comment by harshzalavadiya** [comment]
Hi @flora8984461,

Glad you liked it, This component was built for multiple selection for single selection react-select can be a really good choice
