### ISSUE TITLE
Hide 'Select All' from filtered options

### ISSUE THREAD

**Issue by NotoriousGBG** [harshzalavadiya/react-multi-select-component#46]
Is there a way to hide the Select All option when filtering?

**Comment by harshzalavadiya** [comment]
Hi @NotoriousGBG,

![image](https://user-images.githubusercontent.com/5774849/83643961-59672780-a5ce-11ea-9a07-a98179284390.png)

Do you mean something like above then you can use `hasSelectAll={false}` prop

**Comment by NotoriousGBG** [comment]
Hi @harshzalavadiya,

No I want the Select All there but when I search for 'Grapes', it still shows 'Select All' and 'Grapes'

**Comment by harshzalavadiya** [comment]
Hi @NotoriousGBG,

I got your point as it can be confusing if user selects "select all" and it actully selects everything which is wrong so it will be hidden if you are filtering options
