### ISSUE TITLE
Small UI improvements

### ISSUE THREAD

**Issue by polosson** [harshzalavadiya/react-multi-select-component#5]
First of, thanks for this nice and simple little component!

I'd like to propose a few small improvements to the IU:

- Use different colors for `:hover` state and `.selected` class. Maybe by providing a `--rmsc-selected` CSS var.
- The DOM element `.item-renderer` does not inherits the `cursor: pointer`, which results in a weird behavior of the cursor: we have `default` cursor when hovering the text and checkbox, but `pointer` cursor in the border of the box (in the padding surrounding it). It would be nice to have it consistent.
- The margins of items should be defined, to avoid inconsistency between the "select-all" which is into a `label` element, and other options which are wrapped in `ul > li` elements.

Nice work, by the way!

**Comment by harshzalavadiya** [comment]
@polosson 
Thank you , I have made changes according to suggestions available in `react-multi-select-component@v2.0.2`

**Comment by polosson** [comment]
That's neat! Many thanks to you :smile: !

I just have tested it and that's almost perfect; the "spacing" thing wasn't exactly what I meant, sorry if I was unclear... I meant the spacing (margin) underneath the `<li />` of options. I think it should be defined to `margin-bottom: 0`, because some CSS frameworks (like `tent-css` for example) may set the `li`'s margins globally, and here we really need them to be not spaced, IMHO :smiley:.

BTW, the improvements you made are sufficient and I thank you again!
Cheers

**Comment by harshzalavadiya** [comment]
@polosson 
oh, generally I don't want to make changes for framework spacific resets as I want it to be as lean as possible plus style overrides can be applied easily
but yes in this case setting `margin:0` might be a good idea as similar issue may happen in multiple UI libraries

anyways published in `react-multi-select-component@v2.0.3`
