### ISSUE TITLE
Mod request - Add Prop to declare callback() for when the dropdown list is closed.

### ISSUE THREAD

**Issue by tomjmcnamee** [harshzalavadiya/react-multi-select-component#53]
**Modification Request - Add new Prop to declare callback function when the dropdown list is closed.**
![image](https://user-images.githubusercontent.com/38674764/85047944-8be15a80-b160-11ea-8a3f-ba9a4eb88d27.png)

Hello - I am trying to send your 'selected' hook's data to a global store via redux action, to then update a chart component with the multi-selected data sets.  Global state is successfully updated with 'selected' data upon component render (each time a new checkbox is clicked).  My chart fails to render due to: 
`Warning: Cannot update a component ('Dropdown') while rendering a different component ('ChartBuilder').`
and
`Warning: unstable_flushDiscreteUpdates: Cannot flush updates when React is already rendering.`

I believe I can get around this issue if I were able to call the action as a declared callback function upon closing the checklist dropdown. 

-------------------------
This feature is needed on the below application so multiple state's data can be aggregated into each line of a line chart.
www.corona.tomjmcnamee.com

**Comment by harshzalavadiya** [comment]
Hi @tomjmcnamee,

Can you provide minimal reproduction in codesandbox?

**Comment by tomjmcnamee** [comment]
I was able to get your dropdown to work with Redux by configuring your 'value' and 'onChange' parameters to a redux global store array and action, respectively.  
My failures were from my attempt to use redux with the hooks from your example FC. 
Thanks for the great tool and hard work!
```
<MultiSelect
   options={dropdownOptions}
   value={this.props.multiSelectedStatesIdsArr}
   onChange={this.props.setMultiSelectedStates}
   labelledBy={"Select"}
   hasSelectAll
/>
```
