### ISSUE TITLE
Option to disable 'All items are selected.' text

### ISSUE THREAD

**Issue by Jipperism** [harshzalavadiya/react-multi-select-component#54]
I would like to be able to disable the 'All items are selected' text in the header, and always use the comma-separated list that is normally used.

**Comment by Jipperism** [comment]
Discovered the `valueRenderer` prop while reading the source code, which does the trick as well. Might be good to add this to documentation?

**Comment by harshzalavadiya** [comment]
Hi @Jipperism,

Thanks for the suggestion, I have updated [documentation](https://github.com/harshzalavadiya/react-multi-select-component#-custom-value-renderer) for the same
