### ISSUE TITLE
Is it possible to customize the Checkbox style? 

### ISSUE THREAD

**Issue by ryanadhi** [harshzalavadiya/react-multi-select-component#57]
it would be nice if we have ability to style the checkbox? or probably overriding the css manually like w3school (https://www.w3schools.com/howto/howto_css_custom_checkbox.asp) ?

**Comment by harshzalavadiya** [comment]
@ryanadhi,

well it's quiet easy you can use `ItemRenderer` prop and customize option UI

https://github.com/harshzalavadiya/react-multi-select-component#-custom-item-renderer
