### ISSUE TITLE
Expand disabled dropdown?

### ISSUE THREAD

**Issue by mkhbragg** [harshzalavadiya/react-multi-select-component#67]
Is there a reason that the dropdown is still expandable when it's disabled? If not, here's a teeny tiny PR to address that 👉 https://github.com/harshzalavadiya/react-multi-select-component/pull/66. If it is intentional, could you explain why?

Thanks! And thank you for this component 🙏

**Comment by mkhbragg** [comment]
Looking at [WAI-ARIA focusability guidelines](https://www.w3.org/TR/wai-aria-practices/#kbd_disabled_controls), an alternative to preventing expansion of the dropdown would be to allow the options of a disabled multi-select to be read-only but still focusable. In that case, the behavior might best be addressed along with https://github.com/harshzalavadiya/react-multi-select-component/issues/63.

**Comment by harshzalavadiya** [comment]
@mkhbragg,

Thank you for the PR, I think disabling expansion will be better as of now

PR changes available in v2.0.13
