### ISSUE TITLE
'Select All' is selected for a split second whenever opening the dropdown

### ISSUE THREAD

**Issue by Roeefl** [harshzalavadiya/react-multi-select-component#68]
This happens on your CodeSandbox demo as well.

We just hadn't noticed it when we started using the library.

Is there any way to avoid or resolve this?

**Comment by harshzalavadiya** [comment]
@Roeefl ,

Thanks for reporting this issue, fixed in 2.0.14

**Comment by Roeefl** [comment]
@harshzalavadiya Thanks.
