### ISSUE TITLE
I am trying to apply this multi select in multiple input drop down but for every drop down it's giving same values after selection, SO how we can apply this to multiple input fields. So how can i make this multi select to each input field in a form .

### ISSUE THREAD

**Issue by prashantup1993** [harshzalavadiya/react-multi-select-component#77]
Please help me asap

**Comment by harshzalavadiya** [comment]
@prashantup1993,

Can you provide minimal codesandbox exmaple?

**Comment by prashantup1993** [comment]
Here are two fields where i have applied this multi select but if i select in one drop down it's automatically selected in another drop down

                      <Label htmlFor="select">Job Type</Label>
                    </Col>
                    <Col xs="3" md="3">
                      <MultiSelect
                          options={this.state.options}
                          value={this.state.selected}
                           onChange={this.setSelected}
                    </Col>                   
                  </FormGroup>
                  <FormGroup row>
                    <Col md="2">
                      <Label htmlFor="select">Account Segment</Label>
                    </Col>
                    <Col xs="3" md="3">
                    <MultiSelect
                          options={this.state.options}
                          value={this.state.selected}
                          onChange={this.setSelected}
                           />
                    </Col>



<img width="651" alt="multiselect_dropdown" src="https://user-images.githubusercontent.com/28883869/88058371-0139b400-cb81-11ea-9d63-aade8f3c6d93.png">

**Comment by harshzalavadiya** [comment]
It seems that you are assigning same state to assign value and using the same `setSelected` function so this will happen if you use different variable there should be no issues

this is not related to this or any component library.
So, If you are still looking for help prefer asking it on stackoverflow, you will get faster and understandable solution :smile:
