### ISSUE TITLE
Issues with theming 

### ISSUE THREAD

**Issue by Karmagrinder** [harshzalavadiya/react-multi-select-component#78]
Can you provide an example for theming, I am unable to change the theme by using className prop, as mentioned here: 
https://www.npmjs.com/package/react-multi-select-component#-themeing

**Comment by harshzalavadiya** [comment]
Hi @Karmagrinder,

You don;t have to provide `className` prop you can customize it by just overwriting CSS variables 

https://codesandbox.io/s/gallant-hofstadter-5yjuw

Closing this feel free to open if not resolved

**Comment by Karmagrinder** [comment]
Thanks for quick response, for some reason the style properties in multi-select css class are getting overwritten by the internally generated class named ".go355775859". In the sandbox it's working fine. 
But I managed to get things working by using "!important" in the multi-select.

**Comment by harshzalavadiya** [comment]
@Karmagrinder
I think i'll add note for important if it doesn't work
