### ISSUE TITLE
labelledBy prop not working

### ISSUE THREAD

**Issue by UtkarshChandel** [harshzalavadiya/react-multi-select-component#81]
labelledBy Prop dosen't reflect any changes..show "Select" value.

```tsx
<MultiSelect
  hasSelectAll={false}
  id="examClasses"
  name="examClasses"
  options={classesDropdown}
  value={values.selected}
  onChange={(e) => {
    setFieldValue("selected", [...e]);
  }}
  onBlur={handleBlur}
  labelledBy={"Select Classes"}
/>
```

`labelledBy={"Select Classes"}/>`
 _also tried_
`labelledBy = "Select Classes"`

O/P
IMG : 

![selectProp](https://user-images.githubusercontent.com/19821787/88804897-2a36f600-d1cc-11ea-8cf1-52ccb47549da.PNG)

**Comment by harshzalavadiya** [comment]
hi @UtkarshChandel 

`labelledBy` is for `aria-labelledby` attribute you should use `overrideStrings` prop to change placeholder text

```tsx
<MultiSelect
  overrideStrings={{"selectSomeItems": "Custom Select Placeholder..."}}
  // Other Props
/>
```

**Comment by UtkarshChandel** [comment]
Thanks alot 👍
