### ISSUE TITLE
Dropdown is not closed when clicking away on another input

### ISSUE THREAD

**Issue by andreyoganesyan** [harshzalavadiya/react-multi-select-component#82]
Hi,
I've noticed some strange behavior whenever I try to close the dropdown by clicking away. When I click on some empty space, it works fine, however,  when I click on another input, that input receives the focus but the dropdown is not closed.

As far as I understand, the issue is with [these lines of code](https://github.com/harshzalavadiya/react-multi-select-component/blob/1caae76accfeb5df83ff40a04646e2fc881c9e60/src/multi-select/dropdown.tsx#L114) in `dropdown.tsx`: 
```  const handleBlur = (e) => {
    if (!e.relatedTarget) {
      setHasFocus(false);
      setExpanded(false);
    }
  };
```
Since another input is receiving the focus with this click, [e.relatedTarget is defined and contains that new input](https://developer.mozilla.org/en-US/docs/Web/API/FocusEvent/relatedTarget), which means that `setExpanded(false)` is not called. 

I see that this check has been purposefully added, but I'm not sure exactly why. @harshzalavadiya could you please shed some light on it?

**Comment by harshzalavadiya** [comment]
Hi @andreyoganesyan,

Thanks for reporting and detailed analysys, basically this was used to detact outside click but instead of `e.relatedTarget` I should be checking if `e.relatedTarget` is in `e.currentTarget` instead of just doing defined check

Anyways it's fixed in `v3.0.1`
