### ISSUE TITLE
Non-null assertions can only be used in TypeScript files. while building the project

### ISSUE THREAD

**Issue by prashantup1993** [harshzalavadiya/react-multi-select-component#84]
hi when i am uploading my project to pro env it's showing Non-null assertions can only be used in TypeScript files. while building the project , Can you help me in this?

**Comment by harshzalavadiya** [comment]
@prashantup1993 

Can you create codesandbox reproduction?

**Comment by harshzalavadiya** [comment]
closing due to no reproduction
